name: Tests
on:
  pull_request:
    branches:
      - main
      - stage
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: saloon
      DB_USERNAME: root
      DB_PASSWORD: password
      BROADCAST_CONNECTION: log
      CACHE_STORE: array

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: ${{env.DB_PASSWORD}}
          MYSQL_DATABASE: ${{env.DB_DATABASE}}
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Chckout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Running tests
        run: php vendor/bin/pest
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
